/*
 * Telaradio C ABI — auto-generated by cbindgen.
 * Do not edit by hand; regenerate with `cargo build -p telaradio-ffi` (or
 * `make ffi` from the workspace root).
 */

#ifndef TELARADIO_FFI_H
#define TELARADIO_FFI_H

#pragma once

#include <stdint.h>
#include <stddef.h>

/* Forward declarations for types owned by other crates in the workspace. */
typedef struct TrRecipe TrRecipe;
typedef struct TrWavBuffer TrWavBuffer;


/**
 * Opaque cancel token exposed to C callers. Wraps a [`CancellationToken`]
 * which is `Arc<AtomicBool>`-backed and cheap to clone.
 */
typedef struct TrCancelToken TrCancelToken;

/**
 * Returns the last error message set by an FFI call on this thread, or
 * null if no error is pending. The pointer is owned by the FFI; do not
 * free. Successful calls clear this; subsequent reads will see null
 * until the next failure.
 */
const char *tr_last_error(void);

/**
 * Parse a recipe from a NUL-terminated UTF-8 JSON string.
 * Returns an owned pointer or null on failure.
 *
 * # Safety
 * `json` must be a valid NUL-terminated C string or null.
 */
TrRecipe *tr_recipe_parse(const char *json);

/**
 * Free a `Recipe` previously returned by [`tr_recipe_parse`]. Null is a no-op.
 *
 * # Safety
 * `recipe` must be a pointer returned by `tr_recipe_parse` and not yet freed,
 * or null.
 */
void tr_recipe_free(TrRecipe *recipe);

/**
 * Construct a new `WavBuffer` from a samples array. Samples are copied;
 * the caller may free their input array after this call returns.
 *
 * # Safety
 * `samples` must be a valid pointer to `len` consecutive f32 values, or
 * null with `len == 0`.
 */
TrWavBuffer *tr_wavbuffer_new(const float *samples,
                              uintptr_t len,
                              uint32_t sample_rate,
                              uint8_t channels);

/**
 * Run the mock 440 Hz sine subprocess to produce a `WavBuffer`. Spawns
 * `python3 <script_path>`, sends one NDJSON request, reads the response,
 * reads the WAV the subprocess writes, and returns the buffer.
 *
 * # Safety
 * `script_path` and `prompt` must be valid NUL-terminated UTF-8 C strings.
 */
TrWavBuffer *tr_generate_mock(const char *script_path,
                              const char *prompt,
                              uint64_t seed,
                              uint32_t duration_seconds);

/**
 * Apply amplitude modulation. Returns a new owned buffer; the input
 * buffer is unchanged. `envelope_kind`: 0 = Square, 1 = Sine, 2 = Triangle.
 *
 * # Safety
 * `input` must be a valid `WavBuffer` pointer (returned by another
 * `tr_*` function and not yet freed) or null.
 */
TrWavBuffer *tr_apply_am(const TrWavBuffer *input,
                         double rate_hz,
                         double depth,
                         uint32_t envelope_kind);

/**
 * Free a `WavBuffer` previously returned by an FFI function. Null is a no-op.
 *
 * # Safety
 * `buffer` must be a pointer returned by `tr_wavbuffer_new`,
 * `tr_generate_mock`, or `tr_apply_am`, and not yet freed; or null.
 */
void tr_wavbuffer_free(TrWavBuffer *buffer);

/**
 * Borrow the contiguous samples of a `WavBuffer`. Pointer is valid until
 * the buffer is freed.
 *
 * # Safety
 * `buffer` must be a valid `WavBuffer` pointer or null.
 */
const float *tr_wavbuffer_samples(const TrWavBuffer *buffer);

/**
 * Sample count (interleaved across channels) of a `WavBuffer`. Returns 0 if null.
 *
 * # Safety
 * `buffer` must be a valid `WavBuffer` pointer or null.
 */
uintptr_t tr_wavbuffer_len(const TrWavBuffer *buffer);

/**
 * Sample rate of a `WavBuffer` in Hz. Returns 0 if null.
 *
 * # Safety
 * `buffer` must be a valid `WavBuffer` pointer or null.
 */
uint32_t tr_wavbuffer_sample_rate(const TrWavBuffer *buffer);

/**
 * Channel count of a `WavBuffer`. Returns 0 if null.
 *
 * # Safety
 * `buffer` must be a valid `WavBuffer` pointer or null.
 */
uint8_t tr_wavbuffer_channels(const TrWavBuffer *buffer);

/**
 * Allocate a new cancellation token. Never returns null.
 *
 * The returned pointer is owned by the caller; free with
 * [`tr_cancel_token_free`].
 */
struct TrCancelToken *tr_cancel_token_new(void);

/**
 * Signal cancellation on `token`. Safe to call on null (no-op).
 *
 * # Safety
 * `token` must be a valid pointer returned by [`tr_cancel_token_new`]
 * and not yet freed, or null.
 */
void tr_cancel_token_cancel(struct TrCancelToken *token);

/**
 * Free a cancel token. Safe to call on null (no-op).
 *
 * # Safety
 * `token` must be a pointer returned by [`tr_cancel_token_new`] and not
 * yet freed, or null.
 */
void tr_cancel_token_free(struct TrCancelToken *token);

/**
 * Total bytes the ACE-Step model footprint occupies once
 * [`tr_ensure_model_download`] finishes. UI code can use this as the
 * denominator for a download progress bar.
 */
uint64_t tr_ace_step_total_bytes(void);

/**
 * Free a C string previously returned by [`tr_ensure_model_download`] or
 * [`tr_ensure_model_use_existing`]. Safe to call on null (no-op).
 *
 * **The returned strings from `tr_ensure_model_*` MUST be freed via this
 * function.** Do not pass them to C's `free()` — Rust's allocator must
 * reclaim them.
 *
 * # Safety
 * `ptr` must be a `*mut c_char` returned by one of the `tr_ensure_model_*`
 * functions and not yet freed, or null.
 */
void tr_string_free(char *ptr);

/**
 * Download the ACE-Step model artifacts into `install_dir`, resuming any
 * partial download. Returns the install directory as a NUL-terminated C
 * string on success; the caller must free it with [`tr_string_free`].
 * Returns null on failure; call [`tr_last_error`] for the reason.
 *
 * **Thread-safety contract for `progress_cb`:** the callback fires on
 * whatever OS thread the blocking download runs on — *not* the calling
 * thread. Swift callers must marshal back to the main actor inside the
 * callback (e.g. `Task { @MainActor in … }`). The `ctx` pointer is passed
 * through opaquely; Rust never dereferences it, but it must remain valid
 * for the duration of the call.
 *
 * # Safety
 * - `install_dir` must be a valid NUL-terminated UTF-8 C string.
 * - `ctx` is caller-managed; see thread-safety note above.
 * - `cancel` must be a valid [`TrCancelToken`] pointer or null.
 */
char *tr_ensure_model_download(const char *install_dir,
                               void (*progress_cb)(void*, uint64_t),
                               void *ctx,
                               const struct TrCancelToken *cancel);

/**
 * Copy model weights from an existing local directory into `install_dir`,
 * validating sha256 checksums. Returns the install directory as a
 * NUL-terminated C string on success; the caller must free it with
 * [`tr_string_free`]. Returns null on failure; call [`tr_last_error`] for
 * the reason.
 *
 * # Safety
 * `install_dir` and `source_dir` must be valid NUL-terminated UTF-8 C
 * strings.
 */
char *tr_ensure_model_use_existing(const char *install_dir, const char *source_dir);

/**
 * Run ACE-Step generation from a resolved model directory. Spawns the
 * ACE-Step Python subprocess, generates audio, and drops the subprocess.
 *
 * Yes, this incurs subprocess startup per call (~few seconds). Phase 1e
 * (background buffer queue) will add a persistent subprocess; this
 * spawn-use-drop pattern is the minimal correct path for Phase 1d2.
 *
 * Returns an owned `WavBuffer`; the caller must free it with
 * [`tr_wavbuffer_free`]. Returns null on failure; call [`tr_last_error`].
 *
 * # Safety
 * `model_dir` and `prompt` must be valid NUL-terminated UTF-8 C strings.
 */
TrWavBuffer *tr_generate_ace_step(const char *model_dir,
                                  const char *prompt,
                                  uint64_t seed,
                                  uint32_t duration_seconds);

#endif  /* TELARADIO_FFI_H */
